### ISSUE TITLE
Future dev roadmap

### ISSUE THREAD

**Issue by outfittracker** [outfittracker/outfittracker#35]
- [ ] Player stats
- [x] Outfit stats : weapons & vehicles revamp
- [x] General weapon and vehicles stats
- [ ] Various stats : population
- [x] Try to extend the data retention (from one month to twelve, 500 M records 80 GB of data)
- [x] Migration to a more powerful server (Xeon 8 core 32g)
- [ ] Revamp of the live stats 
- [x] Dedup stats data (get rid of some huge tables)
- [ ] Figure a way to calculate outfit resources
- [ ] Add more global ranking
- [x] Solve the infantry ranking problem once and for all
- [ ] Expose some parts of the API to third party dev
- [ ] Use elastic search at some point for the outfit browser
- [x] Prerender some pages, storage via Redis
